//
// CreateConversationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateConversationRequest: Codable {
    public var ttlHours: Int?

    public init(ttlHours: Int? = nil) {
        self.ttlHours = ttlHours
    }
}
