//
// CreateMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateMessageRequest: Codable {
    public var ciphertext: String
    public var nonce: String
    public var tag: String?

    public init(ciphertext: String, nonce: String, tag: String? = nil) {
        self.ciphertext = ciphertext
        self.nonce = nonce
        self.tag = tag
    }
}
