//
// MessageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MessageResponse: Codable {
    public var id: UUID?
    public var ciphertext: String?
    public var nonce: String?
    public var tag: String?
    public var createdAt: Date?
    public var expiresAt: Date?
    public var readAt: Date?
    public var consumed: Bool?

    public init(id: UUID? = nil, ciphertext: String? = nil, nonce: String? = nil, tag: String? = nil, createdAt: Date? = nil, expiresAt: Date? = nil, readAt: Date? = nil, consumed: Bool? = nil) {
        self.id = id
        self.ciphertext = ciphertext
        self.nonce = nonce
        self.tag = tag
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.readAt = readAt
        self.consumed = consumed
    }
}
