//
// StatsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StatsResponse: Codable {
    public var date: Date?
    public var messagesCreated: Int64?
    public var messagesRead: Int64?
    public var activeMessages: Int64?
    public var totalConsumedMessages: Int64?

    public init(date: Date? = nil, messagesCreated: Int64? = nil, messagesRead: Int64? = nil, activeMessages: Int64? = nil, totalConsumedMessages: Int64? = nil) {
        self.date = date
        self.messagesCreated = messagesCreated
        self.messagesRead = messagesRead
        self.activeMessages = activeMessages
        self.totalConsumedMessages = totalConsumedMessages
    }
}
