//
// SubscriptionStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SubscriptionStatusResponse: Codable {
    public var status: String?
    public var expiresAt: Date?
    public var maxMessageSizeBytes: Int64?
    public var active: Bool?

    public init(status: String? = nil, expiresAt: Date? = nil, maxMessageSizeBytes: Int64? = nil, active: Bool? = nil) {
        self.status = status
        self.expiresAt = expiresAt
        self.maxMessageSizeBytes = maxMessageSizeBytes
        self.active = active
    }
}
