//
// VerifyReceiptRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VerifyReceiptRequest: Codable {
    public var deviceId: String
    public var receiptData: String

    public init(deviceId: String, receiptData: String) {
        self.deviceId = deviceId
        self.receiptData = receiptData
    }
}
