//
// SubscriptionControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech

import Foundation
import Combine
import OpenAPITransport


open class SubscriptionControllerAPI {
    private let transport: OpenAPITransport
    public var encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .formatted(OpenISO8601DateFormatter())
        return encoder
    }()
    public var decoder: JSONDecoder = {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .formatted(OpenISO8601DateFormatter())
        return decoder
    }()
    public var baseURL = URL(string: "http://localhost:8687")

    public init(_ transport: OpenAPITransport) {
        self.transport = transport
    }


    /// - GET /api/subscription/limits/{deviceId}
    /// - parameter deviceId: (path)  
    /// - returns: AnyPublisher<[String: [String: Any]], Error> 
    open func getSubscriptionLimits(deviceId: String) -> AnyPublisher<[String: [String: Any]], Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/api/subscription/limits/{deviceId}"
                localVarPath = localVarPath.replacingOccurrences(of: "{deviceId}", with: deviceId)
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<[String: [String: Any]], Error> in 
            return self.transport.send(request: request)
                .tryMap { response in
                    if let object = try JSONSerialization.jsonObject(with: response.data, options: []) as? [String: [String: Any]] {
                        return object
                    } else {
                        throw OpenAPITransportError.invalidResponseMappingError(data: response.data)
                    }
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }


    /// - GET /api/subscription/status/{deviceId}
    /// - parameter deviceId: (path)  
    /// - returns: AnyPublisher<SubscriptionStatusResponse, Error> 
    open func getSubscriptionStatus(deviceId: String) -> AnyPublisher<SubscriptionStatusResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/api/subscription/status/{deviceId}"
                localVarPath = localVarPath.replacingOccurrences(of: "{deviceId}", with: deviceId)
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<SubscriptionStatusResponse, Error> in 
            return self.transport.send(request: request)
                .tryMap { response in
                    try self.decoder.decode(SubscriptionStatusResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }


    /// - POST /api/subscription/verify
    /// - parameter verifyReceiptRequest: (body)  
    /// - returns: AnyPublisher<SubscriptionStatusResponse, Error> 
    open func verifySubscription(verifyReceiptRequest: VerifyReceiptRequest) -> AnyPublisher<SubscriptionStatusResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/api/subscription/verify"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                request.httpBody = try self.encoder.encode(verifyReceiptRequest)
                request.setValue("application/json", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<SubscriptionStatusResponse, Error> in 
            return self.transport.send(request: request)
                .tryMap { response in
                    try self.decoder.decode(SubscriptionStatusResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }
}
